services:
  edpofactory:
    build:
      context: workflow-service/
      dockerfile: Dockerfile
    ports:
      - 8080:8080
    depends_on:
      - kafka
    networks:
      - edpofactory

  factorysimulation:
    build:
      context: projectTest/
      dockerfile: Dockerfile
    ports:
      - 8081:8081
    depends_on:
      - kafka
    networks:
      - edpofactory

  zookeeper:
    image: "bitnami/zookeeper:latest"
    hostname: zookeeper
    networks:
      - edpofactory
    ports:
      - 2181:2181
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ALLOW_ANONYMOUS_LOGIN: 'yes'

  kafka:
    image: "bitnami/kafka:latest"
    hostname: kafka
    networks:
      - edpofactory
    ports:
      - 9092:9092
      - 7203:7203
    environment:
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_PORT: 9092
      KAFKA_ADVERTISED_HOST_NAME: 192.168.0.12
      ALLOW_PLAINTEXT_LISTENER: 'yes'
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_LISTENERS: PLAINTEXT://:9092
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    depends_on:
      - zookeeper

networks:
  edpofactory:
    driver: bridge