spring:
  kafka:
    bootstrap-servers: kafka:9092

server:
  port: 8086

zeebe.client:
  cloud:
    region: bru-2
    clusterId: 153106de-81cd-4346-87fa-d4d5c579755b
    clientId: xV7~BfZbgNNRLRhPUjlwY8O2QTTqolLh
    clientSecret: ogy8CFzTt66A2yRg.b~w~2k67-ep57jIMoW4.-Q~fam2b_PC0K14vORHZcA~m5Qb
