spring:
  kafka:
    bootstrap-servers: kafka:9092

server:
  port: 8086

# https://github.com/camunda-community-hub/spring-zeebe#configuring-camunda-platform-8-saas-connection
# https://github.com/camunda-community-hub/spring-zeebe#additional-configuration-options

zeebe.client:
  cloud:
    region: syd-1
    clusterId: ad3b0231-67b1-4db4-a79e-78c38368693a
    clientId: 9YUBOeyJRUAs8jXoqAkQNoRgOA8-63mN
    clientSecret: qvT24mEkchV.sEzecB~LZ3D35Zjl8~rLPO_wH5n3IuW.w2cXfBQnVudRQPPYqRIc
