spring.datasource.url: jdbc:h2:file:./camunda-h2-database

kafka:
  bootstrap-address: kafka:9092
  group-id: order
  trusted-packages: ch.unisg.order.dto

server:
  port: 8080

# https://github.com/camunda-community-hub/spring-zeebe#configuring-camunda-platform-8-saas-connection
# https://github.com/camunda-community-hub/spring-zeebe#additional-configuration-options

zeebe.client:
  cloud:
    region: syd-1
    clusterId: ad3b0231-67b1-4db4-a79e-78c38368693a
    clientId: rGIiwc.r9ouoRsQyLLoPgDLodpRbHQ5K
    clientSecret: NK-PO4Ws-rMsdzLNoBcTzTVlIffP4oR~zUeWcuv6.OWTD1ChFYsJpZjxhIn4XmyT
