camunda.bpm.client:
  base-url: http://order:8080/engine-rest
  worker-id: delivery
  basic-auth:
    username: demo
    password: demo
    subscriptions:
      delivery: # topic name of the External Service Task
        variable-names: []
        process-definition-key: delivery # only filter for External Tasks with this process definition key
