kafka:
  bootstrap-address: kafka:9092
  group-id: warehouse
  trusted-packages: ch.unisg.warehouse.kafka.dto
  producer:
    key-serializer: org.apache.kafka.common.serialization.StringSerializer
    value-serializer: org.springframework.kafka.support.serializer.JsonSerializer

server:
  port: 8081

zeebe.client:
  cloud:
    region: bru-2
    clusterId: 153106de-81cd-4346-87fa-d4d5c579755b
    clientId: xV7~BfZbgNNRLRhPUjlwY8O2QTTqolLh
    clientSecret: ogy8CFzTt66A2yRg.b~w~2k67-ep57jIMoW4.-Q~fam2b_PC0K14vORHZcA~m5Qb