camunda.bpm.client:
  base-url: http://order:8080/engine-rest
  worker-id: warehouse
  basic-auth:
    username: demo
    password: demo
    subscriptions:
      warehouse: # topic name of the External Service Task
        variable-names: []
        process-definition-key: warehouse # only filter for External Tasks with this process definition key


kafka:
  bootstrap-address: kafka:9092
  group-id: warehouse
  trusted-packages: ch.unisg.warehouse.dto