server:
  port: 8081

spring:
  kafka:
    bootstrap-servers: kafka:9092
    consumer:
      auto-offset-reset: earliest


mqtt:
  broker: tcp://broker.hivemq.com
  topics:
    factory: ch/unisg/edpo/group1/factory